---
- name: Install Podman on the VM
  include_tasks: install.yml

- name: Build image from the VM
  include_tasks: build.yml

- name: Push image in to Azure Container Registry (ACR)
  include_tasks: push.yml
