---
- name: Log in to ACR from the VM
  command: >
    podman login {{ acr_login_server }} 
    -u {{ acr_username }} 
    --password {{ acr_password }}

- name: Tag image for ACR
  command: >
    podman tag {{ image_name }}:{{ image_tag }} 
    {{ acr_login_server }}/{{ image_name }}:{{ image_tag }}

- name: Push image to ACR from the VM
  command: >
    podman push {{ acr_login_server }}/{{ image_name }}:{{ image_tag }}
