---
- name: Pull StackEdit image from Docker Hub
  command: >
    podman pull docker.io/benweet/stackedit-base:latest
  become: yes

- name: Tag StackEdit image for ACR
  command: >
    podman tag docker.io/benweet/stackedit-base:latest {{ acr_name }}.azurecr.io/{{ image_name_stackedit }}:{{ image_tag_stackedit }}
  become: yes

- name: Push StackEdit image to ACR
  command: >
    podman push {{ acr_name }}.azurecr.io/{{ image_name_stackedit }}:{{ image_tag_stackedit }}
  become: yes
