all:
  children:
    azure_vm:
      hosts:
        vm-weu-cp2-docs:
          ansible_host: 52.233.185.96
          ansible_user: charlstown
          ansible_ssh_private_key_file: ~/.ssh/az_unir_rsa
          ansible_python_interpreter: "{{ lookup('env', 'VIRTUAL_ENV') + '/bin/python' }}"

    azure_acr:
      hosts:
        acrweucp2dev:
          acr_login_server: acrweucp2dev.azurecr.io

    azure_aks:
      hosts:
        aks-weu-cp2:
          aks_resource_group: rg-weu-cp2
          ansible_connection: local
          ansible_python_interpreter: "{{ lookup('env', 'VIRTUAL_ENV') + '/bin/python' }}"

  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: "{{ lookup('env', 'VIRTUAL_ENV') + '/bin/python' }}"
