all:
  children:
    azure_vm:
        hosts:
            vm-weu-cp2-docs:
                ansible_host: 23.97.197.68
                ansible_user: charlstown
                ansible_ssh_private_key_file: ~/.ssh/az_unir_rsa
                ansible_python_interpreter: /usr/bin/python3

    azure_acr:
        hosts:
            acrweucp2dev:
                acr_login_server: acrweucp2dev.azurecr.io
