- name: Install Podman and Run ACR Container
  hosts: azure_vm
  become: yes
  tasks:

    # ✅ Asegurarse de que el sistema esté actualizado
    - name: Update system packages
      apt:
        update_cache: yes
        upgrade: yes

    # ✅ Instalar Podman
    - name: Install Podman
      apt:
        name: podman
        state: present

    # ✅ Crear directorio de autenticación para Podman
    - name: Ensure auth directory exists
      file:
        path: /root/.config/containers
        state: directory
        mode: '0755'

    # ✅ Iniciar sesión en Azure Container Registry (ACR) usando el módulo `community.general.podman_login`
    - name: Log in to Azure Container Registry (ACR)
      community.general.podman_login:
        registry: "{{ acr_name }}.azurecr.io"
        username: "{{ acr_username }}"
        password: "{{ acr_password }}"

    # ✅ Descargar la imagen del contenedor desde ACR con `community.general.podman_image`
    - name: Pull container image from ACR
      community.general.podman_image:
        name: "{{ acr_name }}.azurecr.io/{{ image_name }}"
        tag: "{{ image_tag }}"
        state: present

    # ✅ Ejecutar el contenedor con `community.general.podman_container`
    - name: Run container from ACR image
      community.general.podman_container:
        name: mkdocs_container
        image: "{{ acr_name }}.azurecr.io/{{ image_name }}:{{ image_tag }}"
        state: started
        restart_policy: always
        ports:
          - "80:80"
