- name: Install Podman and Run ACR Container
  hosts: azure_vm
  become: yes
  tasks:

    # ✅ Asegurarse de que el sistema esté actualizado
    - name: Update system packages
      apt:
        update_cache: yes
        upgrade: yes

    # ✅ Instalar Podman
    - name: Install Podman
      apt:
        name: podman
        state: present

    # ✅ Iniciar sesión en Azure Container Registry (ACR)
    - name: Log into Azure Container Registry (ACR)
      containers.podman.podman_login:
        registry: "{{ acr_name }}.azurecr.io"
        username: "{{ acr_username }}"
        password: "{{ acr_password }}"

    # ✅ Descargar la imagen del contenedor desde ACR
    - name: Pull container image from ACR
      containers.podman.podman_image:
        name: "{{ acr_name }}.azurecr.io/{{ image_name }}"
        tag: "{{ image_tag }}"
        state: present

    # ✅ Ejecutar el contenedor
    - name: Run container from ACR image
      containers.podman.podman_container:
        name: mkdocs_container
        image: "{{ acr_name }}.azurecr.io/{{ image_name }}:{{ image_tag }}"
        state: started
        restart_policy: always
        ports:
          - "80:80"

    # ✅ Generar un servicio systemd para hacer el contenedor persistente
    - name: Generate systemd service for Podman container
      containers.podman.podman_generate_systemd:
        name: mkdocs_container
        dest: /etc/systemd/system/
        restart_policy: always

    # ✅ Habilitar y arrancar el servicio systemd para que se inicie en cada reinicio
    - name: Enable and start Podman container systemd service
      systemd:
        name: container-mkdocs_container
        enabled: yes
        state: started
        daemon_reload: yes
