name: Publish release MkDocs Nginx to ACR

on:
  workflow_dispatch:
    inputs:
      acr_name:
        description: "Azure Container Registry Name"
        required: true
        default: "acrdevweucp2"  # ✅ Default ACR Name
      acr_username:
        description: "Azure Container Registry Username"
        required: true
      acr_password:
        description: "Azure Container Registry Password"
        required: true
        type: string

env:
  IMAGE_NAME: "mkdocs-nginx"
  TAG: "latest"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      
      # ✅ Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # ✅ Iniciar sesión en ACR con las credenciales ingresadas
      - name: Log in to Azure Container Registry
        run: |
          echo "${{ github.event.inputs.acr_password }}" | docker login ${{ github.event.inputs.acr_name }}.azurecr.io -u ${{ github.event.inputs.acr_username }} --password-stdin

      # ✅ Instalar MkDocs
      - name: Install MkDocs
        run: |
          pip install mkdocs
          mkdocs build

      # ✅ Construir imagen Docker con el sitio MkDocs dentro de Nginx
      - name: Build Docker Image
        run: |
          docker build -t ${{ github.event.inputs.acr_name }}.azurecr.io/$IMAGE_NAME:$TAG .

      # ✅ Subir imagen a ACR
      - name: Push Image to ACR
        run: |
          docker push ${{ github.event.inputs.acr_name }}.azurecr.io/$IMAGE_NAME:$TAG
