name: Build & Push MkDocs Nginx to ACR

on:
  workflow_dispatch:  # Permite ejecución manual

env:
  ACR_NAME: ${{ secrets.AZURE_ACR_NAME }}
  IMAGE_NAME: "mkdocs-nginx"
  TAG: "latest"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      
      # ✅ Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # ✅ Iniciar sesión en Azure
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # ✅ Iniciar sesión en ACR
      - name: Log in to Azure Container Registry
        run: |
          az acr login --name $ACR_NAME

      # ✅ Instalar MkDocs
      - name: Install MkDocs
        run: |
          pip install mkdocs
          mkdocs build

      # ✅ Construir imagen Docker con el sitio MkDocs dentro de Nginx
      - name: Build Docker Image
        run: |
          docker build -t $ACR_NAME/$IMAGE_NAME:$TAG .

      # ✅ Subir imagen a ACR
      - name: Push Image to ACR
        run: |
          docker push $ACR_NAME/$IMAGE_NAME:$TAG
